// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QueueLess.Data;

#nullable disable

namespace QueueLess.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260121161409_SeedInitialDatas")]
    partial class SeedInitialDatas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QueueLess.Models.Queue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AverageServiceTimeMinutes")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("ServiceLocationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ServiceLocationId");

                    b.ToTable("Queues");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AverageServiceTimeMinutes = 30,
                            CreatedOn = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Engine oil and oil filter replacement.",
                            IsOpen = true,
                            Name = "Oil Change Service",
                            ServiceLocationId = 1
                        },
                        new
                        {
                            Id = 2,
                            AverageServiceTimeMinutes = 45,
                            CreatedOn = new DateTime(2026, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Brake system inspection and diagnostics.",
                            IsOpen = true,
                            Name = "Brake Inspection",
                            ServiceLocationId = 1
                        },
                        new
                        {
                            Id = 3,
                            AverageServiceTimeMinutes = 25,
                            CreatedOn = new DateTime(2026, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Classic men's haircut and styling.",
                            IsOpen = true,
                            Name = "Men's Haircut",
                            ServiceLocationId = 2
                        },
                        new
                        {
                            Id = 4,
                            AverageServiceTimeMinutes = 20,
                            CreatedOn = new DateTime(2026, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Routine dental examination.",
                            IsOpen = true,
                            Name = "Dental Check-up",
                            ServiceLocationId = 3
                        },
                        new
                        {
                            Id = 5,
                            AverageServiceTimeMinutes = 40,
                            CreatedOn = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Smartphone screen replacement service.",
                            IsOpen = true,
                            Name = "Phone Screen Replacement",
                            ServiceLocationId = 4
                        });
                });

            modelBuilder.Entity("QueueLess.Models.QueueEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("JoinedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("QueueId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QueueId");

                    b.ToTable("QueueEntries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientName = "Ivan Petrov",
                            JoinedOn = new DateTime(2026, 1, 15, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            QueueId = 1
                        },
                        new
                        {
                            Id = 2,
                            ClientName = "Georgi Dimitrov",
                            JoinedOn = new DateTime(2026, 1, 15, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            QueueId = 1
                        },
                        new
                        {
                            Id = 3,
                            ClientName = "Petar Kolev",
                            JoinedOn = new DateTime(2026, 1, 15, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            QueueId = 3
                        },
                        new
                        {
                            Id = 4,
                            ClientName = "Maria Ivanova",
                            JoinedOn = new DateTime(2026, 1, 15, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            QueueId = 4
                        },
                        new
                        {
                            Id = 5,
                            ClientName = "Nikolay Stoyanov",
                            JoinedOn = new DateTime(2026, 1, 15, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            QueueId = 5
                        });
                });

            modelBuilder.Entity("QueueLess.Models.ServiceLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("ServiceLocations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "12 Industrial Street, Sofia",
                            CreatedOn = new DateTime(2026, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "AutoFix Garage",
                            PhoneNumber = "+359888123456"
                        },
                        new
                        {
                            Id = 2,
                            Address = "8 Main Blvd, Plovdiv",
                            CreatedOn = new DateTime(2026, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Downtown Barber Shop",
                            PhoneNumber = "+359887222333"
                        },
                        new
                        {
                            Id = 3,
                            Address = "25 Health St, Varna",
                            CreatedOn = new DateTime(2026, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Smile Dental Clinic",
                            PhoneNumber = "+359889333444"
                        },
                        new
                        {
                            Id = 4,
                            Address = "14 Tech Ave, Sofia",
                            CreatedOn = new DateTime(2026, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "SmartFix Phone Repair",
                            PhoneNumber = "+359886444555"
                        },
                        new
                        {
                            Id = 5,
                            Address = "1 Freedom Sq, Burgas",
                            CreatedOn = new DateTime(2026, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Municipal Services Office",
                            PhoneNumber = "+359885555666"
                        });
                });

            modelBuilder.Entity("QueueLess.Models.Queue", b =>
                {
                    b.HasOne("QueueLess.Models.ServiceLocation", "ServiceLocation")
                        .WithMany()
                        .HasForeignKey("ServiceLocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceLocation");
                });

            modelBuilder.Entity("QueueLess.Models.QueueEntry", b =>
                {
                    b.HasOne("QueueLess.Models.Queue", null)
                        .WithMany("QueueEntries")
                        .HasForeignKey("QueueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QueueLess.Models.Queue", b =>
                {
                    b.Navigation("QueueEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
