// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QueueLess.Data;

#nullable disable

namespace QueueLess.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("QueueLess.Models.Queue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AverageServiceTimeMinutes")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("bit");

                    b.Property<int>("MaxWaitMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("ServiceLocationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ServiceLocationId");

                    b.ToTable("Queues");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AverageServiceTimeMinutes = 30,
                            CreatedOn = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Engine oil and oil filter replacement.",
                            IsOpen = true,
                            MaxWaitMinutes = 0,
                            Name = "Oil Change Service",
                            ServiceLocationId = 1
                        },
                        new
                        {
                            Id = 2,
                            AverageServiceTimeMinutes = 45,
                            CreatedOn = new DateTime(2026, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Brake system inspection and diagnostics.",
                            IsOpen = true,
                            MaxWaitMinutes = 0,
                            Name = "Brake Inspection",
                            ServiceLocationId = 1
                        },
                        new
                        {
                            Id = 3,
                            AverageServiceTimeMinutes = 25,
                            CreatedOn = new DateTime(2026, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Classic men's haircut and styling.",
                            IsOpen = true,
                            MaxWaitMinutes = 0,
                            Name = "Men's Haircut",
                            ServiceLocationId = 2
                        },
                        new
                        {
                            Id = 4,
                            AverageServiceTimeMinutes = 20,
                            CreatedOn = new DateTime(2026, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Routine dental examination.",
                            IsOpen = true,
                            MaxWaitMinutes = 0,
                            Name = "Dental Check-up",
                            ServiceLocationId = 3
                        },
                        new
                        {
                            Id = 5,
                            AverageServiceTimeMinutes = 40,
                            CreatedOn = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Smartphone screen replacement service.",
                            IsOpen = true,
                            MaxWaitMinutes = 0,
                            Name = "Phone Screen Replacement",
                            ServiceLocationId = 4
                        });
                });

            modelBuilder.Entity("QueueLess.Models.QueueEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("JoinedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("QueueId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QueueId");

                    b.ToTable("QueueEntries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientName = "Ivan Petrov",
                            JoinedOn = new DateTime(2026, 1, 15, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            QueueId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            ClientName = "Georgi Dimitrov",
                            JoinedOn = new DateTime(2026, 1, 15, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            QueueId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = 3,
                            ClientName = "Petar Kolev",
                            JoinedOn = new DateTime(2026, 1, 15, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            QueueId = 3,
                            Status = 0
                        },
                        new
                        {
                            Id = 4,
                            ClientName = "Maria Ivanova",
                            JoinedOn = new DateTime(2026, 1, 15, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            QueueId = 4,
                            Status = 0
                        },
                        new
                        {
                            Id = 5,
                            ClientName = "Nikolay Stoyanov",
                            JoinedOn = new DateTime(2026, 1, 15, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            QueueId = 5,
                            Status = 0
                        });
                });

            modelBuilder.Entity("QueueLess.Models.ServiceLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("ServiceLocations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "12 Industrial Street, Sofia",
                            CreatedOn = new DateTime(2026, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "AutoFix Garage",
                            PhoneNumber = "+359888123456"
                        },
                        new
                        {
                            Id = 2,
                            Address = "8 Main Blvd, Plovdiv",
                            CreatedOn = new DateTime(2026, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Downtown Barber Shop",
                            PhoneNumber = "+359887222333"
                        },
                        new
                        {
                            Id = 3,
                            Address = "25 Health St, Varna",
                            CreatedOn = new DateTime(2026, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Smile Dental Clinic",
                            PhoneNumber = "+359889333444"
                        },
                        new
                        {
                            Id = 4,
                            Address = "14 Tech Ave, Sofia",
                            CreatedOn = new DateTime(2026, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "SmartFix Phone Repair",
                            PhoneNumber = "+359886444555"
                        },
                        new
                        {
                            Id = 5,
                            Address = "1 Freedom Sq, Burgas",
                            CreatedOn = new DateTime(2026, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Municipal Services Office",
                            PhoneNumber = "+359885555666"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QueueLess.Models.Queue", b =>
                {
                    b.HasOne("QueueLess.Models.ServiceLocation", "ServiceLocation")
                        .WithMany()
                        .HasForeignKey("ServiceLocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceLocation");
                });

            modelBuilder.Entity("QueueLess.Models.QueueEntry", b =>
                {
                    b.HasOne("QueueLess.Models.Queue", null)
                        .WithMany("QueueEntries")
                        .HasForeignKey("QueueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QueueLess.Models.Queue", b =>
                {
                    b.Navigation("QueueEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
